### ISSUE TITLE
Error: Unsupported request method: kotlin/buildOutputLocation

### ISSUE THREAD

**Issue by C-Lunn** [fwcd/vscode-java-kotlin#7]
Hi all, I tried installing this extension as I _believe_ it should resolve the 'cannot be resolved' error when importing Kotlin classes into a Java file.

I built and installed the extension according to the readme file, but on trying to use it I still get the cannot be resolved errors, and see this in my log:

```
[2022-05-21 14:33:49.140] [exthost] [error] Activating extension fwcd.vscode-java-kotlin failed due to an error:
[2022-05-21 14:33:49.140] [exthost] [error] Error: Unsupported request method: kotlin/buildOutputLocation
    at handleResponse (/home/c/.vscode-server/extensions/fwcd.kotlin-0.2.26/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
    at processMessageQueue (/home/c/.vscode-server/extensions/fwcd.kotlin-0.2.26/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
    at Immediate.<anonymous> (/home/c/.vscode-server/extensions/fwcd.kotlin-0.2.26/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
    at processImmediate (node:internal/timers:464:21)
```
I'm using VSC 1.67.2 on Windows, but I compiled and installed the extension remotely on my Debian 10 development machine.

It's entirely possible that a) I have misunderstood the purpose of this extension, and b) I've done something silly, but if anyone could help I'd appreciate it very much. Cheers.

**Comment by daplf** [comment]
Hey @C-Lunn 

I haven't looked at this in a while, but I think what you're missing is the latest code for the [kotlin-language-server](https://github.com/fwcd/kotlin-language-server). The latest [changes that make this possible](https://github.com/fwcd/kotlin-language-server/pull/334) were not released yet as far as I'm aware, which means [vscode-kotlin](https://github.com/fwcd/vscode-kotlin/) is not yet using them.

To make this work for now, you need to build the kotlin-language-server yourself (shouldn't be difficult, take a look at the readme) and use the [kotlin.languageServer.path](https://github.com/fwcd/vscode-kotlin/blob/main/package.json#L212-L216) property from `vscode-kotlin` to let the extension know where the server executable is located.

**Comment by C-Lunn** [comment]
Hi. Many thanks for this. I'll look into it.
